### ISSUE TITLE
add back in array iterations?

### ISSUE THREAD

**Issue by devinrhode2** [hanifbbz/micromustache#1]
micro mustache seems perfect but array iterations would be critical

**Comment by hanifbbz** [comment]
Hi Devin,

You are right but this feature will have negative effects on the performance and code size. There is another relevant feature that I had to decline in order to keep the focus: accessing nested object properties.

Nevertheless, if you have an algorithm that doesn't affect performance, you can submit a pull request and I'll take a look.

**Comment by coderofsalvation** [comment]
micromustache is indeed focusing on performance and codesize, try brown instead (a fork of micromustache with focus on more features):

https://www.npmjs.com/package/brown
https://www.npmjs.com/package/brown-ext-basic
https://www.npmjs.com/package/brown-express

**Comment by userpixel** [comment]
Great job @coderofsalvation.
Brown seems to be a very good alternative.
